const DATA={
 videos:[['squat','Squat','Këmbë & glute','Mbaj gjoksin lart dhe gjunjët në vijë me shputat.'],['pushup','Push-up','Gjoks & triceps','Trupi në një vijë; mos e lësho belin.'],['plank','Plank','Core','Shtrëngo barkun dhe gluteusët.'],['lunge','Lunge','Këmbë','Ulu me kontroll dhe mbaj gjurin stabil.'],['curl','Biceps curl','Krahë','Bërrylat qëndrojnë pranë trupit.'],['jumpingjack','Jumping jack','Kardio','Zbrit butë dhe mbaj ritëm të kontrolluar.']],
 muscles:['Të gjitha','Gjoks','Shpinë','Këmbë','Shpatulla','Krahë','Core'],
 exercises:[
 ['Gjoks','Push-up','3 × 8–15','Trupi drejt, bërrylat 30–45°.'],['Gjoks','Incline push-up','3 × 10–15','Më e lehtë; duart në një sipërfaqe të ngritur.'],['Shpinë','Back extension','3 × 12','Lëviz ngadalë, mos e tepro me harkimin.'],['Shpinë','Bird-dog','3 × 10/anë','Mbaj legenin stabil.'],['Këmbë','Squat','4 × 8–12','Pesha mbi mes të shputës.'],['Këmbë','Reverse lunge','3 × 10/anë','Hap prapa dhe mbaj ekuilibrin.'],['Shpatulla','Pike push-up','3 × 6–12','Shty kokën mes duarve.'],['Shpatulla','Lateral raise','3 × 12–15','Ngrit deri në lartësinë e shpatullave.'],['Krahë','Biceps curl','3 × 10–15','Pa lëkundje të trupit.'],['Krahë','Bench dip','3 × 8–12','Shpatullat poshtë, bërrylat prapa.'],['Core','Plank','3 × 30–60 sek','Mos e lësho belin.'],['Core','Dead bug','3 × 10/anë','Shpina e poshtme në dysheme.']
 ],
 stations:[['SomaFM Groove Salad','https://ice1.somafm.com/groovesalad-128-mp3'],['SomaFM Beat Blender','https://ice1.somafm.com/beatblender-128-mp3'],['SomaFM PopTron','https://ice1.somafm.com/poptron-128-mp3']],
 plan:[['Hënë','Gjoks + triceps'],['Martë','Ecje 30 min'],['Mërkurë','Shpinë + biceps'],['Enjte','Pushim aktiv'],['Premte','Këmbë + core'],['Shtunë','Kardio e lehtë'],['Diel','Pushim']]
};
const T={sq:{home:'Kreu',videos:'Video',exercises:'Ushtrime',calculators:'Kalkulatorë',nutrition:'Ushqim',radio:'Radio',eyebrow:'FITNES PËR JETËN REALE',hero:'Ndërto trupin.<br><em>Forco mendjen.</em>',intro:'Video praktike, plane ushtrimesh, kalkulatorë dhe këshilla të thjeshta për rezultate reale.',watch:'Shiko videot',calculate:'Llogarit tani',videoCount:'video lokale',toolsCount:'mjete praktike',languages:'gjuhë',daily:'Misioni i sotëm',dailyText:'30 minuta stërvitje. Zero arsyetime.',videoTitle:'Video të ushtrimeve',videoDesc:'Video të integruara në ZIP; punojnë edhe pa internet.',exerciseTitle:'Zgjidh pjesën e trupit',exerciseDesc:'Kliko një kategori për ushtrime dhe udhëzime.',calcTitle:'Kalkulatorë fitnesi',calcDesc:'Vlera orientuese, jo diagnozë mjekësore.',sex:'Gjinia',age:'Mosha',weight:'Pesha (kg)',height:'Gjatësia (cm)',activity:'Aktiviteti',calculateBtn:'Llogarit',nutritionTitle:'Bazat e ushqimit',nutritionDesc:'Thjesht, pa premtime boshe.',proteinTitle:'Proteina',proteinText:'Ndihmon ruajtjen dhe ndërtimin e muskujve. Synim i zakonshëm: 1.6–2.2 g/kg për persona aktivë.',carbTitle:'Karbohidrate',carbText:'Burim kryesor energjie për stërvitje. Zgjidh oriz, patate, tërshërë, fruta dhe perime.',fatTitle:'Yndyra të mira',fatText:'Të rëndësishme për hormone dhe shëndet. Përdor vaj ulliri, arra, peshk dhe avokado.',radioTitle:'Radio për stërvitje',radioDesc:'Stream-et kërkojnë internet dhe mund të ndryshojnë nga ofruesi.',nowPlaying:'Tani luan',planTitle:'Plan i thjeshtë javor',contactTitle:'Gati për ndryshim?',contactText:'Puno me durim, mat progresin dhe mos kërko rezultate të menjëhershme.',cookieText:'Kjo faqe përdor cookies bazë dhe mund të përdorë reklama nga Google AdSense.',accept:'Prano'},
de:{home:'Start',videos:'Videos',exercises:'Übungen',calculators:'Rechner',nutrition:'Ernährung',radio:'Radio',eyebrow:'FITNESS FÜR DAS ECHTE LEBEN',hero:'Baue deinen Körper.<br><em>Stärke deinen Geist.</em>',intro:'Praktische Videos, Trainingspläne, Rechner und klare Tipps für echte Ergebnisse.',watch:'Videos ansehen',calculate:'Jetzt berechnen',videoCount:'lokale Videos',toolsCount:'praktische Tools',languages:'Sprachen',daily:'Heutige Mission',dailyText:'30 Minuten Training. Keine Ausreden.',videoTitle:'Übungsvideos',videoDesc:'Videos sind im ZIP enthalten und funktionieren offline.',exerciseTitle:'Körperbereich wählen',exerciseDesc:'Wähle eine Kategorie für Übungen und Hinweise.',calcTitle:'Fitness-Rechner',calcDesc:'Orientierungswerte, keine medizinische Diagnose.',sex:'Geschlecht',age:'Alter',weight:'Gewicht (kg)',height:'Größe (cm)',activity:'Aktivität',calculateBtn:'Berechnen',nutritionTitle:'Ernährungsgrundlagen',nutritionDesc:'Einfach und ohne leere Versprechen.',proteinTitle:'Protein',proteinText:'Unterstützt Muskelerhalt und -aufbau. Häufiger Zielbereich: 1,6–2,2 g/kg bei aktiven Menschen.',carbTitle:'Kohlenhydrate',carbText:'Hauptenergiequelle fürs Training. Nutze Reis, Kartoffeln, Hafer, Obst und Gemüse.',fatTitle:'Gute Fette',fatText:'Wichtig für Hormone und Gesundheit. Nutze Olivenöl, Nüsse, Fisch und Avocado.',radioTitle:'Workout-Radio',radioDesc:'Streams benötigen Internet und können sich beim Anbieter ändern.',nowPlaying:'Jetzt läuft',planTitle:'Einfacher Wochenplan',contactTitle:'Bereit für Veränderung?',contactText:'Arbeite geduldig, miss deinen Fortschritt und erwarte keine Sofortergebnisse.',cookieText:'Diese Website nutzt grundlegende Cookies und kann Google-AdSense-Werbung verwenden.',accept:'Akzeptieren'},
en:{home:'Home',videos:'Videos',exercises:'Exercises',calculators:'Calculators',nutrition:'Nutrition',radio:'Radio',eyebrow:'FITNESS FOR REAL LIFE',hero:'Build your body.<br><em>Strengthen your mind.</em>',intro:'Practical videos, workout plans, calculators and clear guidance for real results.',watch:'Watch videos',calculate:'Calculate now',videoCount:'local videos',toolsCount:'practical tools',languages:'languages',daily:"Today's mission",dailyText:'30 minutes of training. No excuses.',videoTitle:'Exercise videos',videoDesc:'Videos are included in the ZIP and work offline.',exerciseTitle:'Choose a body area',exerciseDesc:'Select a category for exercises and guidance.',calcTitle:'Fitness calculators',calcDesc:'Estimates only, not medical diagnosis.',sex:'Sex',age:'Age',weight:'Weight (kg)',height:'Height (cm)',activity:'Activity',calculateBtn:'Calculate',nutritionTitle:'Nutrition basics',nutritionDesc:'Simple, without empty promises.',proteinTitle:'Protein',proteinText:'Supports muscle retention and growth. Common target: 1.6–2.2 g/kg for active people.',carbTitle:'Carbohydrates',carbText:'Main training fuel. Choose rice, potatoes, oats, fruit and vegetables.',fatTitle:'Healthy fats',fatText:'Important for hormones and health. Use olive oil, nuts, fish and avocado.',radioTitle:'Workout radio',radioDesc:'Streams require internet and may change at the provider.',nowPlaying:'Now playing',planTitle:'Simple weekly plan',contactTitle:'Ready to change?',contactText:'Work patiently, measure progress and do not expect instant results.',cookieText:'This site uses basic cookies and may use Google AdSense advertising.',accept:'Accept'}};
let lang=localStorage.getItem('nk_lang')||((navigator.language||'').startsWith('de')?'de':(navigator.language||'').startsWith('sq')?'sq':'sq');
function applyLang(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;if(T[lang][k])e.textContent=T[lang][k]});document.querySelectorAll('[data-i18n-html]').forEach(e=>{const k=e.dataset.i18nHtml;if(T[lang][k])e.innerHTML=T[lang][k]});document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('nk_lang',lang)}
document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;applyLang()});
const videoGrid=document.getElementById('videoGrid');DATA.videos.forEach(v=>{const a=document.createElement('article');a.className='video-card';a.innerHTML=`<video src="videos/${v[0]}.mp4" muted loop playsinline preload="metadata"></video><div class="pad"><h3>${v[1]}</h3><p>${v[2]}</p><button class="btn">▶ Open</button></div>`;a.querySelector('video').onmouseenter=e=>e.target.play();a.querySelector('video').onmouseleave=e=>{e.target.pause();e.target.currentTime=0};a.querySelector('button').onclick=()=>openVideo(v);videoGrid.appendChild(a)});
function openVideo(v){document.getElementById('modalVideo').src=`videos/${v[0]}.mp4`;document.getElementById('modalTitle').textContent=v[1];document.getElementById('modalText').textContent=v[3];document.getElementById('videoModal').classList.add('open')}
const chips=document.getElementById('muscleChips'),grid=document.getElementById('exerciseGrid');function renderExercises(filter='Të gjitha'){grid.innerHTML='';DATA.exercises.filter(x=>filter==='Të gjitha'||x[0]===filter).forEach(x=>{const a=document.createElement('article');a.className='exercise-card';a.innerHTML=`<span class="tag">${x[0]}</span><h3>${x[1]}</h3><strong>${x[2]}</strong><p>${x[3]}</p>`;grid.appendChild(a)})}DATA.muscles.forEach((m,i)=>{const b=document.createElement('button');b.textContent=m;b.className=i===0?'active':'';b.onclick=()=>{document.querySelectorAll('#muscleChips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderExercises(m)};chips.appendChild(b)});renderExercises();
let calc='bmi';document.querySelectorAll('[data-calc]').forEach(b=>b.onclick=()=>{calc=b.dataset.calc;document.querySelectorAll('[data-calc]').forEach(x=>x.classList.remove('active'));b.classList.add('active');calculate()});document.getElementById('calcForm').onsubmit=e=>{e.preventDefault();calculate()};function calculate(){const w=+weight.value,h=+height.value,a=+age.value,s=sex.value,act=+activity.value;let val,label,text;if(calc==='bmi'){val=(w/((h/100)**2)).toFixed(1);label='BMI';text=val<18.5?'Nën peshë':val<25?'Interval normal':val<30?'Mbi peshë':'Obezitet — konsultohu me mjekun'}else if(calc==='calories'){let bmr=10*w+6.25*h-5*a+(s==='male'?5:-161);val=Math.round(bmr*act);label='kcal/ditë';text='Mirëmbajtje e përafërt'}else if(calc==='protein'){val=`${Math.round(w*1.6)}–${Math.round(w*2.2)}`;label='g proteinë/ditë';text='Interval i zakonshëm për persona aktivë'}else{val=Math.round(w*35);label='ml ujë/ditë';text='Rregullo sipas vapës dhe aktivitetit'}resultLabel.textContent=label;resultValue.textContent=val;resultText.textContent=text}calculate();
const stations=document.getElementById('stations'),audio=document.getElementById('audio');DATA.stations.forEach((s,i)=>{const b=document.createElement('button');b.textContent=`${i+1}. ${s[0]}`;b.onclick=()=>{audio.src=s[1];audio.play().catch(()=>{});stationName.textContent=s[0];document.querySelectorAll('.stations button').forEach(x=>x.classList.remove('active'));b.classList.add('active')};stations.appendChild(b)});audio.src=DATA.stations[0][1];
const planGrid=document.getElementById('planGrid');DATA.plan.forEach((d,i)=>{const x=document.createElement('article');x.className='day';x.innerHTML=`<strong>${i+1}</strong><h3>${d[0]}</h3><p>${d[1]}</p>`;planGrid.appendChild(x)});
let count=+(sessionStorage.getItem('nk_online')||Math.floor(780+Math.random()*670));function tick(){count+=Math.floor(Math.random()*17)-8;count=Math.max(780,Math.min(1450,count));onlineCount.textContent=count.toLocaleString();sessionStorage.setItem('nk_online',count)}tick();setInterval(tick,4200);
menuBtn.onclick=()=>nav.classList.toggle('open');document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
document.querySelectorAll('.modal .close').forEach(b=>b.onclick=()=>{b.closest('.modal').classList.remove('open');const v=b.closest('.modal').querySelector('video');if(v){v.pause();v.src=''}});document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});
const legal={privacy:'<h2>Privacy</h2><p>NKBEASTS mund të përdorë cookies, matje trafiku dhe Google AdSense. Të dhënat personale nuk shiten. Kontakt: xhatikk@hotmail.com.</p>',terms:'<h2>Terms</h2><p>Përmbajtja është informuese. Përdorimi bëhet me përgjegjësinë e vizitorit.</p>',medical:'<h2>Medical disclaimer</h2><p>Informacioni nuk zëvendëson mjekun, diagnozën ose trajtimin. Konsultohu me profesionist shëndetësor para ndryshimeve të mëdha.</p>'};document.querySelectorAll('[data-legal]').forEach(b=>b.onclick=()=>{legalContent.innerHTML=legal[b.dataset.legal];legalModal.classList.add('open')});
if(localStorage.getItem('nk_cookie')==='yes')cookie.classList.add('hide');acceptCookie.onclick=()=>{localStorage.setItem('nk_cookie','yes');cookie.classList.add('hide')};applyLang();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
