(() => {
  const T = {
    sq: {nav:'SHOP',title:'PAJISJE & VESHJE',gloves:'Doreza fitnesi',glovesText:'Kapje më e sigurt dhe mbrojtje për duart gjatë ushtrimeve.',belt:'Rrip ngritjeje',beltText:'Mbështetje për belin gjatë squat, deadlift dhe ngritjeve të rënda.',shirt:'T-shirt sportive',shirtText:'Bluzë sportive me logon NKBEASTS për palestër dhe përdorim të përditshëm.',shoes:'Atlete sportive',shoesText:'Atlete për stërvitje, ecje dhe performancë të përditshme.',cap:'Kapelë sportive',capText:'Kapelë e lehtë me dizajn të pastër dhe logon NKBEASTS.',shorts:'Shorce sportive',shortsText:'Shorce të rehatshme për palestër, vrapim dhe stërvitje intensive.',socks:'Çorape sportive',socksText:'Çorape sportive të rehatshme me logon NKBEASTS.',bag:'Çantë fitnesi',bagText:'Hapësirë për rroba, këpucë, shaker dhe pajisjet e stërvitjes.',shaker:'Shaker & shishe',shakerText:'Për ujë, proteinë dhe pije sportive gjatë gjithë ditës.',coming:'SË SHPEJTI',note:'Ky është prezantimi i koleksionit. Shitja nuk aktivizohet derisa produktet, çmimet dhe furnizuesi të jenë gati.'},
    de: {nav:'SHOP',title:'AUSRÜSTUNG & BEKLEIDUNG',gloves:'Trainingshandschuhe',glovesText:'Sicherer Griff und Schutz für die Hände beim Training.',belt:'Gewichthebergürtel',beltText:'Unterstützung für den unteren Rücken bei Kniebeugen, Kreuzheben und schweren Übungen.',shirt:'Sport-T-Shirt',shirtText:'Sportshirt mit NKBEASTS-Logo für Training und Alltag.',shoes:'Sportschuhe',shoesText:'Schuhe für Training, Walking und tägliche Leistung.',cap:'Sport-Cap',capText:'Leichte Cap mit klarem Design und NKBEASTS-Logo.',shorts:'Sportshorts',shortsText:'Bequeme Shorts für Fitnessstudio, Laufen und intensives Training.',socks:'Sportsocken',socksText:'Bequeme Sportsocken mit NKBEASTS-Logo.',bag:'Sporttasche',bagText:'Platz für Kleidung, Schuhe, Shaker und Trainingsausrüstung.',shaker:'Shaker & Flasche',shakerText:'Für Wasser, Proteinshakes und Sportgetränke.',coming:'BALD VERFÜGBAR',note:'Dies ist eine Vorschau der Kollektion. Der Verkauf wird erst aktiviert, wenn Produkte, Preise und Lieferant feststehen.'},
    en: {nav:'SHOP',title:'GEAR & APPAREL',gloves:'Training gloves',glovesText:'A safer grip and hand protection during training.',belt:'Lifting belt',beltText:'Lower-back support for squats, deadlifts and heavy lifts.',shirt:'Sports T-shirt',shirtText:'NKBEASTS sports shirt for training and everyday wear.',shoes:'Training shoes',shoesText:'Shoes for training, walking and everyday performance.',cap:'Sports cap',capText:'Lightweight cap with a clean design and NKBEASTS logo.',shorts:'Sports shorts',shortsText:'Comfortable shorts for the gym, running and intense workouts.',socks:'Sports socks',socksText:'Comfortable sports socks with the NKBEASTS logo.',bag:'Gym bag',bagText:'Space for clothes, shoes, shaker and training equipment.',shaker:'Shaker & bottle',shakerText:'For water, protein shakes and sports drinks.',coming:'COMING SOON',note:'This is a collection preview. Sales remain disabled until the products, prices and supplier are ready.'}
  };
  function apply(lang){
    const dict=T[lang]||T.en;
    document.querySelectorAll('[data-shop-i18n]').forEach(el=>{const v=dict[el.dataset.shopI18n]; if(v) el.textContent=v;});
  }
  document.addEventListener('DOMContentLoaded',()=>apply(localStorage.getItem('nk-lang')||document.documentElement.lang||'sq'));
  document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>apply(btn.dataset.lang)));
  window.addEventListener('nk-language-change',e=>apply(e.detail?.lang));
})();
