const i18n = {
  sq:{
    navHome:"Ballina",navWorkouts:"Ushtrime",navNutrition:"Ushqimi",navCalculators:"Kalkulatorë",navNews:"Lajme",navLibrary:"Biblioteka",startNow:"Fillo tani",
    heroEyebrow:"FORCË • DISIPLINË • REZULTATE",heroLine1:"NDËRTO",heroLine2:"VERSIONIN TËND",heroLine3:"MË TË FORTË.",heroText:"Stërvitje të strukturuara, ushqim i mençur dhe mjete praktike për rezultate reale — në çdo moshë.",exploreWorkouts:"Shiko ushtrimet",useCalculators:"Përdor kalkulatorët",statWorkouts:"ushtrime",statCalculators:"kalkulatorë",statLanguages:"gjuhë",scroll:"ZBULO MË SHUMË",
    whyKicker:"PSE NKBEASTS",whyTitle:"GJITHÇKA QË TË DUHET.<br><span>NË NJË VEND.</span>",whyText:"Jo premtime boshe. Vetëm sistem i qartë, mjete të dobishme dhe hapa që mund t’i ndjekësh çdo ditë.",
    feature1Title:"Stërvitje të strukturuara",feature1Text:"Programe për forcë, muskuj, humbje peshe dhe kondicion.",feature2Title:"Ushqim i mençur",feature2Text:"Udhëzime të thjeshta për proteina, kalori dhe vakte të balancuara.",feature3Title:"Mat progresin",feature3Text:"BMI, TDEE, kalori dhe proteina të llogaritura për ty.",
    workoutKicker:"WORKOUT LIBRARY",workoutTitle:"ZGJIDH QËLLIMIN.<br><span>FILLO PUNËN.</span>",workoutText:"Zgjidh një kategori dhe ndiq një plan të qartë për nivelin tënd.",goalMuscle:"RRITJE MUSKULORE",goalStrength:"FORCË",goalConditioning:"KONDICION",pushTitle:"PUSH DAY",pushText:"Gjoks, shpatulla dhe triceps.",pullTitle:"PULL DAY",pullText:"Shpinë, biceps dhe shpatulla e pasme.",legsTitle:"LEGS & CORE",legsText:"Këmbë të forta dhe core stabil.",openPlan:"Hap planin →",
    nutritionBadge:"e rezultateve fillojnë me zakonet",nutritionKicker:"NUTRITION",nutritionTitle:"HA PËR QËLLIMIN.<br><span>JO VETËM PËR SHIJEN.</span>",nutritionText:"Ndërto vakte të thjeshta me proteina, karbohidrate cilësore, yndyrna të mira dhe perime.",proteinTitle:"Proteina",proteinText:"Për rikuperim dhe muskuj.",carbsTitle:"Karbohidratet",carbsText:"Për energji dhe performancë.",fatsTitle:"Yndyrnat e mira",fatsText:"Për hormone dhe shëndet.",
    calcKicker:"FITNESS CALCULATORS",calcTitle:"NUMRAT E TU.<br><span>PLANI YT.</span>",calcText:"Llogarit vlerat bazë dhe përdori si pikënisje — jo si diagnozë mjekësore.",proteinTab:"PROTEINA",waterTab:"UJI",height:"Gjatësia (cm)",weight:"Pesha (kg)",calculate:"Llogarit",gender:"Gjinia",male:"Mashkull",female:"Femër",age:"Mosha",activity:"Aktiviteti",sedentary:"Pak aktiv",light:"1–3 stërvitje/javë",moderate:"3–5 stërvitje/javë",high:"6–7 stërvitje/javë",caloriesDay:"kcal / ditë",goal:"Qëllimi",maintain:"Mirëmbajtje",muscleGain:"Rritje muskulore",fatLoss:"Humbje yndyre",proteinDaily:"PROTEINA / DITË",guideline:"udhëzim i përgjithshëm",trainingMinutes:"Minuta stërvitje",waterDaily:"UJI / DITË",estimate:"vlerësim i përgjithshëm",
    newsKicker:"FITNESS NEWS",newsTitle:"INFORMOHU.<br><span>MOS U HUTO.</span>",refreshNews:"Përditëso lajmet",libraryKicker:"NKBEASTS LIBRARY",libraryTitle:"MËSO. ZBATO.<br><span>PËRSËRIT.</span>",libraryText:"Udhëzime të shkurtra dhe praktike për njerëz që duan rezultate të qëndrueshme.",article1:"Si të fillosh palestrën pas moshës 40 vjeç",article2:"Sa proteina të duhen realisht?",article3:"Deficiti kalorik pa humbur muskuj",readTime:"5 minuta lexim",radioTitle:"ENERGJI PËR ÇDO SET.",radioText:"Radio motivuese gjatë stërvitjes. Shtyp play dhe vazhdo punën.",radioReady:"Gati për play",footerText:"Ndërto forcë. Ha më mirë. Qëndro konsistent.",cookieText:"Kjo faqe përdor cookies për funksionim dhe analiza.",reject:"Refuzo",accept:"Prano"
  },
  de:{
    navHome:"Start",navWorkouts:"Workouts",navNutrition:"Ernährung",navCalculators:"Rechner",navNews:"News",navLibrary:"Bibliothek",startNow:"Jetzt starten",
    heroEyebrow:"KRAFT • DISZIPLIN • ERGEBNISSE",heroLine1:"BAUE",heroLine2:"DEINE STÄRKSTE",heroLine3:"VERSION.",heroText:"Strukturierte Workouts, clevere Ernährung und praktische Tools für echte Ergebnisse — in jedem Alter.",exploreWorkouts:"Workouts ansehen",useCalculators:"Rechner nutzen",statWorkouts:"Übungen",statCalculators:"Rechner",statLanguages:"Sprachen",scroll:"MEHR ENTDECKEN",
    whyKicker:"WARUM NKBEASTS",whyTitle:"ALLES, WAS DU BRAUCHST.<br><span>AN EINEM ORT.</span>",whyText:"Keine leeren Versprechen. Nur ein klares System, nützliche Tools und Schritte, die du täglich umsetzen kannst.",
    feature1Title:"Strukturierte Workouts",feature1Text:"Programme für Kraft, Muskelaufbau, Fettverlust und Kondition.",feature2Title:"Clevere Ernährung",feature2Text:"Einfache Leitlinien für Protein, Kalorien und ausgewogene Mahlzeiten.",feature3Title:"Fortschritt messen",feature3Text:"BMI, TDEE, Kalorien und Protein für dich berechnet.",
    workoutKicker:"WORKOUT BIBLIOTHEK",workoutTitle:"WÄHLE DEIN ZIEL.<br><span>LEG LOS.</span>",workoutText:"Wähle eine Kategorie und folge einem klaren Plan für dein Niveau.",goalMuscle:"MUSKELAUFBAU",goalStrength:"KRAFT",goalConditioning:"KONDITION",pushTitle:"PUSH DAY",pushText:"Brust, Schultern und Trizeps.",pullTitle:"PULL DAY",pullText:"Rücken, Bizeps und hintere Schulter.",legsTitle:"LEGS & CORE",legsText:"Starke Beine und stabiler Core.",openPlan:"Plan öffnen →",
    nutritionBadge:"der Ergebnisse beginnen mit Gewohnheiten",nutritionKicker:"ERNÄHRUNG",nutritionTitle:"ISS FÜR DEIN ZIEL.<br><span>NICHT NUR FÜR DEN GESCHMACK.</span>",nutritionText:"Baue einfache Mahlzeiten aus Protein, hochwertigen Kohlenhydraten, guten Fetten und Gemüse.",proteinTitle:"Protein",proteinText:"Für Regeneration und Muskeln.",carbsTitle:"Kohlenhydrate",carbsText:"Für Energie und Leistung.",fatsTitle:"Gute Fette",fatsText:"Für Hormone und Gesundheit.",
    calcKicker:"FITNESS RECHNER",calcTitle:"DEINE ZAHLEN.<br><span>DEIN PLAN.</span>",calcText:"Berechne Basiswerte und nutze sie als Ausgangspunkt — nicht als medizinische Diagnose.",proteinTab:"PROTEIN",waterTab:"WASSER",height:"Größe (cm)",weight:"Gewicht (kg)",calculate:"Berechnen",gender:"Geschlecht",male:"Mann",female:"Frau",age:"Alter",activity:"Aktivität",sedentary:"Wenig aktiv",light:"1–3 Trainings/Woche",moderate:"3–5 Trainings/Woche",high:"6–7 Trainings/Woche",caloriesDay:"kcal / Tag",goal:"Ziel",maintain:"Erhaltung",muscleGain:"Muskelaufbau",fatLoss:"Fettverlust",proteinDaily:"PROTEIN / TAG",guideline:"allgemeiner Richtwert",trainingMinutes:"Trainingsminuten",waterDaily:"WASSER / TAG",estimate:"allgemeine Schätzung",
    newsKicker:"FITNESS NEWS",newsTitle:"BLEIB INFORMIERT.<br><span>NICHT VERWIRRT.</span>",refreshNews:"News aktualisieren",libraryKicker:"NKBEASTS BIBLIOTHEK",libraryTitle:"LERNEN. UMSETZEN.<br><span>WIEDERHOLEN.</span>",libraryText:"Kurze, praktische Leitfäden für nachhaltige Ergebnisse.",article1:"So startest du mit Fitness ab 40",article2:"Wie viel Protein brauchst du wirklich?",article3:"Kaloriendefizit ohne Muskelverlust",readTime:"5 Minuten Lesezeit",radioTitle:"ENERGIE FÜR JEDEN SATZ.",radioText:"Motivationsradio fürs Training. Play drücken und weitermachen.",radioReady:"Bereit zum Abspielen",footerText:"Stärke aufbauen. Besser essen. Konsequent bleiben.",cookieText:"Diese Website verwendet Cookies für Funktion und Analyse.",reject:"Ablehnen",accept:"Akzeptieren"
  },
  en:{
    navHome:"Home",navWorkouts:"Workouts",navNutrition:"Nutrition",navCalculators:"Calculators",navNews:"News",navLibrary:"Library",startNow:"Start now",
    heroEyebrow:"STRENGTH • DISCIPLINE • RESULTS",heroLine1:"BUILD",heroLine2:"YOUR STRONGEST",heroLine3:"SELF.",heroText:"Structured workouts, smarter nutrition and practical tools for real results — at any age.",exploreWorkouts:"Explore workouts",useCalculators:"Use calculators",statWorkouts:"exercises",statCalculators:"calculators",statLanguages:"languages",scroll:"DISCOVER MORE",
    whyKicker:"WHY NKBEASTS",whyTitle:"EVERYTHING YOU NEED.<br><span>IN ONE PLACE.</span>",whyText:"No empty promises. Just a clear system, useful tools and steps you can follow every day.",
    feature1Title:"Structured workouts",feature1Text:"Programs for strength, muscle, fat loss and conditioning.",feature2Title:"Smarter nutrition",feature2Text:"Simple guidance for protein, calories and balanced meals.",feature3Title:"Measure progress",feature3Text:"BMI, TDEE, calories and protein calculated for you.",
    workoutKicker:"WORKOUT LIBRARY",workoutTitle:"CHOOSE YOUR GOAL.<br><span>DO THE WORK.</span>",workoutText:"Pick a category and follow a clear plan for your level.",goalMuscle:"MUSCLE BUILDING",goalStrength:"STRENGTH",goalConditioning:"CONDITIONING",pushTitle:"PUSH DAY",pushText:"Chest, shoulders and triceps.",pullTitle:"PULL DAY",pullText:"Back, biceps and rear delts.",legsTitle:"LEGS & CORE",legsText:"Strong legs and a stable core.",openPlan:"Open plan →",
    nutritionBadge:"of results begin with habits",nutritionKicker:"NUTRITION",nutritionTitle:"EAT FOR THE GOAL.<br><span>NOT ONLY FOR TASTE.</span>",nutritionText:"Build simple meals with protein, quality carbohydrates, healthy fats and vegetables.",proteinTitle:"Protein",proteinText:"For recovery and muscle.",carbsTitle:"Carbohydrates",carbsText:"For energy and performance.",fatsTitle:"Healthy fats",fatsText:"For hormones and health.",
    calcKicker:"FITNESS CALCULATORS",calcTitle:"YOUR NUMBERS.<br><span>YOUR PLAN.</span>",calcText:"Calculate key estimates and use them as a starting point — not medical advice.",proteinTab:"PROTEIN",waterTab:"WATER",height:"Height (cm)",weight:"Weight (kg)",calculate:"Calculate",gender:"Gender",male:"Male",female:"Female",age:"Age",activity:"Activity",sedentary:"Low activity",light:"1–3 workouts/week",moderate:"3–5 workouts/week",high:"6–7 workouts/week",caloriesDay:"kcal / day",goal:"Goal",maintain:"Maintenance",muscleGain:"Muscle gain",fatLoss:"Fat loss",proteinDaily:"PROTEIN / DAY",guideline:"general guideline",trainingMinutes:"Training minutes",waterDaily:"WATER / DAY",estimate:"general estimate",
    newsKicker:"FITNESS NEWS",newsTitle:"STAY INFORMED.<br><span>NOT CONFUSED.</span>",refreshNews:"Refresh news",libraryKicker:"NKBEASTS LIBRARY",libraryTitle:"LEARN. APPLY.<br><span>REPEAT.</span>",libraryText:"Short, practical guides for people who want sustainable results.",article1:"How to start training after 40",article2:"How much protein do you really need?",article3:"Calorie deficit without losing muscle",readTime:"5 min read",radioTitle:"ENERGY FOR EVERY SET.",radioText:"Motivational radio for your workout. Press play and keep moving.",radioReady:"Ready to play",footerText:"Build strength. Eat smarter. Stay consistent.",cookieText:"This site uses cookies for functionality and analytics.",reject:"Reject",accept:"Accept"
  }
};
